version: '3.9'

services:
  mainframe:
    image: codeanalyser/mainframe
    ports:
      - "8761:8761"
    restart: always
    networks:
      - backend

  openai-agent:
    image: codeanalyser/openai
    ports:
      - "8081:8081"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://mainframe:8761/eureka"
      SPRING_AI_OPENAI_API_KEY: "sk-proj-lVtNiss6Guzm38nASXRoT3BlbkFJ0sSnIseTssK4Nv1YCV65"
    restart: always
    networks:
      - backend
    depends_on:
      - mainframe

  llama-agent:
    image: codeanalyser/llama
    ports:
      - "8082:8082"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://mainframe:8761/eureka"
    restart: always
    networks:
      - backend
    depends_on:
      - mainframe

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    networks:
      - backend
    command: "serve && pull llama3"

  code-storage:
    image: codeanalyser/code-storage
    ports:
      - "8799:8799"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://mainframe:8761/eureka"
      EUREKA_INSTANCE.PREFERIPADDRESS: 'true'
    restart: always
    networks:
      - backend
    depends_on:
      - mainframe

  shop:
    image: codeanalyser/shop
    ports:
      - "8080:8080"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://mainframe:8761/eureka"
    restart: always
    networks:
      - backend
    depends_on:
      - mainframe

  frontend:
    image: codeanalyser/frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_SUPABASE_URL: "https://qmbcqunhrmowgkbxmiqe.supabase.co"
      NEXT_PUBLIC_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtYmNxdW5ocm1vd2drYnhtaXFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTQ5NDM0MDAsImV4cCI6MjAzMDUxOTQwMH0.lAdOxVeJ5QctKiHWxbRCOWwVALfnRaOemTZ4cfjqy0E"
    restart: always
    networks:
      - backend
    depends_on:
      - mainframe

networks:
  backend:
    driver: bridge